name: Harbor Test Workflow

on:
    pull_request:
      types: [opened,reopened,synchronize,closed]

permissions:
    contents: read
    pull-requests: write
    id-token: write

jobs:
    uffizzi-cluster:
        name: Deploy to Uffizzi uCluster
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        # Identify comment to be updated
        - name: Find comment for Ephemeral Environment
          uses: peter-evans/find-comment@v2
          id: find-comment
          with:
            issue-number: ${{ github.event.pull_request.number }}
            comment-author: "github-actions[bot]"
            body-includes: pr-${{ github.event.pull_request.number }}
            direction: last

        # Create/Update comment with action deployment status
        - name: Create or Update Comment with Deployment Notification
          uses: peter-evans/create-or-update-comment@v2
          id: notification
          with:
            comment-id: ${{ steps.find-comment.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
                ## Uffizzi Ephemeral Environment - Virtual Cluster

                :cloud: deploying ...

                :gear: Updating now by workflow run [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
                    Download the Uffizzi CLI to interact with the upcoming virtual cluster
                https://docs.uffizzi.com/install
            edit-mode: replace
    
        # Create/Connect to Uffizzi Virtual Cluster
        - name: Connect to Virtual Cluster
          uses: UffizziCloud/cluster-action@main
          with:
            cluster-name: pr-${{ github.event.pull_request.number }}

        # Create/Update comment with action deployment status
        - name: Create or Update Comment with Deployment URL
          uses: peter-evans/create-or-update-comment@v2
          with:
            comment-id: ${{ steps.notification.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
                ## Uffizzi Ephemeral Environment - Virtual Cluster
        
                Your cluster `pr-${{ github.event.pull_request.number }}` was successfully created. Learn more about [Uffizzi virtual clusters](https://docs.uffizzi.com/virtual-clusters)
                To connect to this cluster, follow these steps:
        
                1. Download and install the Uffizzi CLI from https://docs.uffizzi.com/install
                2. Login to Uffizzi: `uffizzi login`
                3. Update your kubeconfig: `uffizzi cluster update-kubeconfig pr-${{ github.event.pull_request.number }}`. This command will update your local `~/.kube/config`.
                If you want to provide an alternate location follow the optional step (the next step) instead.
        
                    Optional: Update your kubeconfig: `uffizzi cluster update-kubeconfig pr-${{ github.event.pull_request.number }} --kubeconfig=[KUBECONFIG]`, replacing `[KUBECONFIG]` with the path to your kubeconfig file.
                After updating your kubeconfig, you can manage your cluster with `kubectl`, `kustomize`, `helm`, and other tools that use kubeconfig files: `kubectl get namespace --kubeconfig [KUBECONFIG]`
        
            edit-mode: replace

        # Apply Harbor Helm Chart
        - name: Apply Helm Chart
          id: helm
          run: |
            ls
            export KUBECONFIG="`pwd`/kubeconfig"
            helm repo add harbor https://helm.goharbor.io
            helm install my-release harbor/harbor --values=values.yaml

            kubectl delete ingress my-release-harbor-ingress
            kubectl create ingress my-release-harbor-ingress \
                --class=nginx \
                --rule="pr-${{ github.event.pull_request.number }}-harbor.uclusters.app.uffizzi.com/*=my-release-harbor-portal:80,tls"